branches:
  only:
    - main

skip_non_tags: true

image:
  - Visual Studio 2019
install:
  - set QTDIR=C:\Qt\5.15.2\msvc2019_64
  - set PATH=%PATH%;%QTDIR%\bin
build_script:
  - dir
  - cmake -DCMAKE_PREFIX_PATH=%QTDIR% --build . --target all
  - dir
