branches:
  only:
    - main

skip_non_tags: true

image:
  - Visual Studio 2019
install:
  - set QTDIR=C:/Qt/6.0/msvc2019_64
  - set QTIFW=C:/Qt/Tools/QtInstallerFramework
  - set PATH=%PATH%;%QTDIR%/bin;%QTIFW%/bin;C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Auxiliary\Build;%PATH%
  - vcvars64.bat
build_script:
  - md build
  - cd build
  - cmake .. -GNinja -DCMAKE_BUILD_TYPE=Release -DCMAKE_PREFIX_PATH=%QTDIR%
  - cmake --build . --target all
  - cd ..
after_build:
  - (robocopy build/bin installer/packages/com.andreyrk.studyguide/data /E /IS /IT > null) ^& IF %ERRORLEVEL% LEQ 1 exit 0
  - echo Debug
  - binarycreator -c installer/config/config.xml -p installer/packages Instalador_Clerisy.exe
  - echo Debug
deploy:
  provider: GitHub
  description: ''
  artifact: Instalador_Clerisy.exe
  on:
    branch: main
    APPVEYOR_REPO_TAG: true
