branches:
  only:
    - main

skip_non_tags: true

image:
  - Visual Studio 2019
install:
  - set QTDIR=C:\Qt\5.15.2\msvc2019_64
  - set PATH=%PATH%;%QTDIR%\bin
before_build:
  - md build
  - cd build
build_script:
  - cmake .. -GNinja -DCMAKE_BUILD_TYPE=Release -DCMAKE_PREFIX_PATH=%QTDIR%
after_build:
  - dir
  - cd CMakeFiles; dir
